### PR TITLE
LINKTA-118: Update docs file names according to best naming practices

### PR DESCRIPTION
**Pull request by kinskiwu**
## Description
- Update md file names to maintain consistency
- Update PR to comment out heading

Fixes #[LINKTA-118](https://linkta.atlassian.net/browse/LINKTA-118?atlOrigin=eyJpIjoiYjVjNmJkOWYzMGU4NDYzODliYWE3MjMzYzBmMTgxOWYiLCJwIjoiaiJ9) (issue)

## Type of change

- [X] 📝 Documentation update

## Checklist:

- [x] I have made corresponding changes to the documentation.
- [X] I have reviewed the [**Security Best Practices Document**](SECURITY_BEST_PRACTICES.md).
- [X] I have followed the [**Naming Conventions Guide**](NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [X] I have ensured that my pull request title is descriptive.

[LINKTA-118]: https://linkta.atlassian.net/browse/LINKTA-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ChTiSh — COMMENTED** [review]
I find the instruction on github for pull_request_template.md quite confusing. Wondering if we should pull the pull_request_template.md out of the docs folder and route it as: .github/PULL_REQUEST_TEMPLATE/pull_request_template.md

**Comment by ChTiSh** [comment]
Or maybe we can try to change the file name to PULL_REQUEST_TEMPLATE.md to put it in the .github folder instead of docs folder

**Comment by kinskiwu** [comment]
> I find the instruction on github for pull_request_template.md quite confusing. Wondering if we should pull the pull_request_template.md out of the docs folder and route it as: .github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Yes I took a look and found it quite confusing too. Let's create a separate issue for this.

**Review by ChTiSh — APPROVED** [review]

**Review by dcpavel — COMMENTED** [review]
These look good to me.

**Pull request merged**
