### PR TITLE
Incorporates Loader state UI during LLM processing

### LINKED ISSUE #78: As a user, I want to easily submit my input through an intuitive interface and have it processed securely into a structured LinktaFlow
**Describe the solution you'd like**

The user story focuses on providing a seamless and user-friendly experience for submitting input and generating a structured LinktaFlow. It involves designing an intuitive user interface, developing a robust API for handling user input, enhancing the input processing pipeline, and implementing client-side functionality for a smooth user experience.

The goal is to ensure that users can easily share their thoughts and ideas, while the system securely processes and transforms the input into a structured format, ready for further analysis and visualization. The implementation will prioritize data integrity, security, and performance optimization to deliver a reliable and efficient solution.

### LINKED ISSUE #83: Implement loading state UI for user feedback during LLM processing
## Acceptance criteria
- Loading state UI is displayed while waiting for LLM response
- User is informed about the processing status
- Loading state UI is dismissed when the response is received
- The design of the loading state UI aligns with Linkta's branding and visual style
  - Colors, fonts, and iconography should match Linkta's design guidelines
  - The loading state UI should be visually consistent with other UI components in the application
  - The design should provide an intuitive user experience

### PR DESCRIPTION
**Pull request by chrisr0892**
## Description

- Added `Loader` component with MUI `CircularProgress`.
- LoaderStore added to Zustand Stores.
- Loader added to `UserInputForm`
- Loader added to `OutputVisualizationPage` with zustand state to allow for re-rendering when `regenerate` is clicked.

Fixes #78  

## Type of change

- [x] ✨  New feature (non-breaking change which adds functionality)

## How Can this be tested? Testing Plan to review this PR

- [x] Where in the app does this change take place?
  - `UserInputForm.tsx` and `OutputVisualizationPage.tsx`
- [x] What are the steps to test this change?
  - From the `/generate` route:
    - Enter input and click the `Generate` button to create a new LinktaFlow.
  - From the side nav:
    - Click the `•••` icon and select `Regenerate`.
- [x] What is the expected output?
  - An animated circular loader will appear in the center of the screen until LLM processing is finished.
## Checklist:

- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [x] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [x] I have ensured that my pull request title is descriptive.

### CODE REVIEW

**Review by colinvandergraaf — APPROVED** [review]
👍 This looks good!

**Review by kinskiwu — COMMENTED** [review]
Thanks for the good work! 

There's a Loader component in `/components/common`, consider moving the loading functionality from the UserInputForm to this Loader component. Since multiple parts of the app use the Loader, we should make sure this loader is reusable and comprehensive for generic use and add a bit more for LLM interactions.

Currently, the LLM loader is needed in 2 areas so please make sure you incorporate the loader in the respective components. 
- UserInputForm
- OptionsMenu (regenerate function)

For LLM interactions, it'd be great to show additional info to reassure users that the process might take a while due to AI processing. Not a requirement and only if you have the capacity, adding a button for the user to cancel the query could help improve our UX too. 

For styling, if we are making a reusable loader, prioritize using a CSS object over inline styling if time allows.

**Comment by chrisr0892** [comment]
> Thanks for the good work!
> 
> There's a Loader component in `/components/common`, consider moving the loading functionality from the UserInputForm to this Loader component. Since multiple parts of the app use the Loader, we should make sure this loader is reusable and comprehensive for generic use and add a bit more for LLM interactions.
> 
> Currently, the LLM loader is needed in 2 areas so please make sure you incorporate the loader in the respective components.
> 
> * UserInputForm
> * OptionsMenu (regenerate function)
> 
> For LLM interactions, it'd be great to show additional info to reassure users that the process might take a while due to AI processing. Not a requirement and only if you have the capacity, adding a button for the user to cancel the query could help improve our UX too.
> 
> For styling, if we are making a reusable loader, prioritize using a CSS object over inline styling if time allows.

Thanks for the review! I moved the loader to existing Loader.tsx component so that it can be reusable and incorporated it in UserInputForm and OutputVisualizationPage (regenerate).

**Review by kinskiwu — APPROVED** [review]
This looks good. Thanks for the good work Chris!

**Pull request merged**
