### PR TITLE
LINKTA-3: Set up file structure 

### PR DESCRIPTION
**Pull request by dcpavel**
## Description

Construction of the base file structure. Dummy files have been created at low level directories so the tree should fully exist. File names are not fixed at this time, and any changes should adhere to naming conventions listed elsewhere.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- No tests at this time

## Checklist:

Before submitting your pull request, please review the following checklist:

- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Additional Information:

None

### CODE REVIEW

**Comment by dcpavel** [comment]
Closing pull request so that I can properly adhere to PR format.

**Comment by dcpavel** [comment]
Re-opening after seeing that I can actually edit the comments in this form.

**Comment by dcpavel** [comment]
I changed the branch I was merging into as well. I originally had this merging to main, but I saw many of the other initial PRs moving to dev.

**Review by relandboyle — APPROVED** [review]
@dcpavel This looks great.

@ChTiSh @dcpavel As per our conversations, this PR is coming from a forked repository due to a minor communications error at the executive level. Going forward we will create feature branches in the Linkta-org/Core repository.

**Comment by dcpavel** [comment]
> We will have to change the client/ folders to adapt to next.js@LucieSeidler , but we should probably get this in asap

I have a src/app folder which within client, which is the default for Next.js projects, correct?

**Comment by ChTiSh** [comment]
Yeah, I think nextjs requires components to be in app folders and static assets to be in public folder.

**Pull request merged**
