### PR TITLE
Feature/linkta 194 set up private routing for authenticated access

### PR DESCRIPTION
**Pull request by kinskiwu**
## Description

- Implemented a new `ProtectedRoute` component that guards private routes, ensuring they are accessible only to authenticated users.
- Developed the `useAuth` hook to be used within the `ProtectedRoute` component for dynamic access control.
- `privateRoutes` has been updated to utilize the new `ProtectedRoute` component
- `publicRoutes` has been updated to externalize `MainLayout`, promoting a more modular approach to layout management.
- `Router` configuration has been updated to effectively merge public and private routes under a unified `MainLayout` to ensure a consistent layout across the app.
- Added `<ErrorPage />` to router as errorElement
- Created an `authRoutes` file to consolidate all auth routes & refactored `publicRoutes`

@lomeintheory Please review this PR since changes have been made to react-router setup.

Fixes #LINKTA-194

## Type of change

- [X] ✨  New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- [X] Manual testing by running npm run dev:frontend to test routing

## Checklist:

- [X] I have performed a self-review of my own code.
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] Any dependent changes have been merged and published in downstream modules.
- [X] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [X] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [X] I have ensured that my pull request title is descriptive.

## Additional Information:
- `useAuth` hook logic to be implemented later
- TODO:
  - Related to #53
    - Move `ProtectedRoute` from `/routes` to `/auth-pages` folder
    - Replace placeholders in `authRoutes` with actual components

### CODE REVIEW

**Comment by kinskiwu** [comment]
Converted to draft for now before firebase setup pr is merged.

**Review by dcpavel — APPROVED** [review]
Thank you for the inclusion of the TODO comments. Have you made sure that there are issues on the Jira board for these?

**Review by lomeintheory — APPROVED** [review]
Looks great. Comments explain the code really well. Also really appreciate the todo comments.

**Comment by kinskiwu** [comment]
@dcpavel Thanks for clarifying. The to-do is for this pr (currently this pr is a draft). Will remove it when it is ready for review.

**Pull request merged**
