### PR TITLE
LINKTA-116: Update naming conventions doc

### PR DESCRIPTION
**Pull request by kinskiwu**
## Description

- Remove Next.js from doc
- Add additional examples under branch naming
- Link commit message guide to doc

Fixes #[LINKTA-116](https://linkta.atlassian.net/browse/LINKTA-116?atlOrigin=eyJpIjoiNGFmYWQ3MGEwNGJiNGNhNzkzMWY4NDE5OWM0ODNjOWIiLCJwIjoiaiJ9) (issue)

## Type of change

- [X] 📝 Documentation update

## Checklist:

- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] Any dependent changes have been merged and published in downstream modules.
- [X] I have reviewed the [**Security Best Practices Document**](SECURITY_BEST_PRACTICES.md).
- [X] I have followed the [**Naming Conventions Guide**](NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [X] I have ensured that my pull request title is descriptive.

[LINKTA-116]: https://linkta.atlassian.net/browse/LINKTA-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by AnatoliySokolov98 — APPROVED** [review]
Great job.

**Comment by ChTiSh** [comment]
We should probably include a tip for collaborators/contribitors as well, since they won't have access to the Jira board. I will update the contributing guide to instruct non-member collaborators/contributors to fork and then submit a PR.

Also wondering if including jira key in the commit message is necessary for jira to pickup or we can just link the issue in the description.

**Comment by kinskiwu** [comment]
> We should probably include a tip for collaborators/contribitors as well, since they won't have access to the Jira board. I will update the contributing guide to instruct non-member collaborators/contributors to fork and then submit a PR.
> 
> Also wondering if including jira key in the commit message is necessary for jira to pickup or we can just link the issue in the description.

While it is good to have tips for non-core members, it is not a blocker for switching back to React or the MVP. Maybe we can do that after we have the MVP up?

**Comment by ChTiSh** [comment]
True, it shouldn't be a blocking issue right now. Merging.

**Review by ChTiSh — APPROVED** [review]

**Pull request merged**
