### PR TITLE
LINKTA-136: Set up React Router

### PR DESCRIPTION
**Pull request by lomeintheory**
## Description

Set up React Router to define routes for all pages defined in file structure.

## Type of change

- [x] ✨  New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Manual testing

## Checklist:

- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I have reviewed the [**Security Best Practices Document**](SECURITY_BEST_PRACTICES.md).
- [x] I have followed the [**Naming Conventions Guide**](NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [x] I have ensured that my pull request title is descriptive.

## Additional Information:

- Created error page in not-found-page component
- Little to no styling done so far
- Curious to hear feedback on pathnames

### CODE REVIEW

**Review by kinskiwu — CHANGES_REQUESTED** [review]
Great work on the PR! I've looked it over and have a few suggestions that I think will enhance our project's structure and maintainability:

### General Best Practices:
- **Frequent Commits:** Just FYI, committing more frequently with a more focused scope will make it easier to understand and review changes.
- **Simplify File Structure:** Since we have `main.tsx` as our entry file, we should remove the `index.ts` file to avoid confusion.
- **Stick to the Ticket:** Ensure that changes are specific to the ticket you're working on. Modifications related to `NotFoundPage` should be part of its designated ticket and PR.

### PR Specific Notes:
- **Error Handling Components:** It looks like you've worked on `NotFoundPage` for catching all 404 errors. If you're also handling general errors, consider creating an `ErrorPage` component. Both `ErrorPage` and `NotFoundPage` can reside in a renamed folder `error-pages` for better organization. Also remember to clean up NotFoundPage afterwards. [errorElement](https://reactrouter.com/en/main/route/error-element)
- **Routing Logic in `App.tsx`:** It's generally a good practice to keep `main.tsx` clean by using it solely as the entry point and moving routing logic to `App.tsx`.
- **Modularizing Routes:** To follow the SOLID principles for cleaner and more maintainable code, let's organize our routes into separate files/folders within `/client/routes`, distinguishing between `privateRoutes`, `publicRoutes`, and maybe use an `index.tsx` for the router creating. This will simplify adding or modifying routes in the future.
- **Catch-All Route Handler:** Pls incorporate a catch-all route in the routing logic using the `NotFoundPage` to handle undefined routes gracefully. There is no need to add logic to the page as it has its own ticket.
- **Route Naming:** The name `/generate` is a good choice! Since the output page also contains non-tree info, a more generic name than `/tree` could be more fitting.
- **Add Comments:** For any non-obvious logic, such as the array in `createBrowserRouter`, adding comments will greatly aid future maintainability.
- **Private Route:** Since we are incorporating authentication, we'll need to implement a private route wrapper/Layout for private access. I will create a separate ticket for it and one of us can work on it later.

I know this was a big ticket and we should have broken it down a bit more. Thanks again for your hard work on this!

**Comment by dcpavel** [comment]
You will need to remerge with the current version of dev in order to handle these conflicts.

**Comment by kinskiwu** [comment]
I'm currently working on an urgent ticket [LINKTA-179](https://linkta.atlassian.net/browse/LINKTA-179?atlOrigin=eyJpIjoiMWI2NmJhNDJjNTE3NDEzODgwNDMyNTAzOWNkOTE2ZGEiLCJwIjoiaiJ9) which requires me to delete the extra index.ts file, update the main.jsx in index.html to main.tsx, and change main.jsx to main.tsx. Please be aware of merge conflict. Ty!

**Comment by lomeintheory** [comment]
@kinskiwu please take a look at the most recent changes.
Few notes:
- privateRoutes currently has no routes since we haven't defined any auth components yet.
- Changed pathname for tree to output for now (this can be renamed later on if we can think of a better one)
- My comment game is lacking, would love feedback on that as well!
- Everything else I believe we've discussed on Slack

**Review by kinskiwu — APPROVED** [review]
Looks great! Pls carefully handle merge confilcts.

**Review by ChTiSh — APPROVED** [review]
Awesome stuff

**Review by ejwoods — APPROVED** [review]
Nice work! Code looks clean and comments make it easy to follow 👍

**Pull request merged**
