### PR TITLE
LINKTA-72: tsConfig file

### PR DESCRIPTION
**Pull request by zhiyi15**
Description:
moved "include" and "exclude" options outside of compilerOptions object

Fixes # LINKTA-72

Type of change:
🐛 Bug fix (non-breaking change which fixes an issue)
How Has This Been Tested? :
Not yet

Checklist:

I have performed a self-review of my own code.

Additional Information:

### CODE REVIEW

**Comment by ChTiSh** [comment]
I think it's worth noting that this PR is also removing firebase and firebase-admin as dependencies as well.

**Comment by ChTiSh** [comment]
Thank you G!

**Review by dcpavel — APPROVED** [review]
This is the change I needed to make on my local system, so I approve!

**Review by ChTiSh — APPROVED** [review]

**Comment by ChTiSh** [comment]
Merging

**Pull request merged**
