### PR TITLE
LINKTA-122: Add Linting to Github Actions

### PR DESCRIPTION
**Pull request by ChTiSh**
## Description
Add linting to github actions

Fixes: #122

## Type of change
✨  New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
```npx eslint . --ext .js,.jsx,.ts,.tsx```

- [x] I have performed a self-review of my own code.
- [x] I have reviewed the [**Security Best Practices Document**](SECURITY_BEST_PRACTICES.md).
- [x] I have followed the [**Naming Conventions Guide**](NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [x] I have ensured that my pull request title is descriptive.

## Additional Information:
changes made to eslintrc.json to reflect the previous changes of removing nextjs from our project.

warning showing some files cannot be found, this should be resolved once we have our file structure and bundler update

### CODE REVIEW

**Comment by kinskiwu** [comment]
> ## Description
> Add linting to github actions
> 
> Fixes: #122
> 
> ## Type of change
> ✨ New feature (non-breaking change which adds functionality)
> 
> ## How Has This Been Tested?
> `npx eslint . --ext .js,.jsx,.ts,.tsx`
> 
> * [x]  I have performed a self-review of my own code.
> * [x]  I have reviewed the [**Security Best Practices Document**](SECURITY_BEST_PRACTICES.md).
> * [x]  I have followed the [**Naming Conventions Guide**](NAMING_CONVENTIONS_GUIDE.md) for my changes.
> * [x]  I have ensured that my pull request title is descriptive.
> 
> ## Additional Information:
> changes made to eslintrc.json to reflect the previous changes of removing nextjs from our project.
> 
> warning showing some files cannot be found, this should be resolved once we have our file structure and bundler update

Correct me if I am wrong, it seems like next is still in the package.json and the majority of the original dependencies were removed?

**Comment by ChTiSh** [comment]
You are absolutely correct @kinskiwu, just fixed the dependency issue.

**Review by kinskiwu — APPROVED** [review]
Thanks for the update.

**Comment by ChTiSh** [comment]
Hi @dcpavel , just updated the lint script

**Review by dcpavel — CHANGES_REQUESTED** [review]
When running npm run lint with this version on my system, I get a bunch of errors from prettier that prevents prettier from writing the code. I think that line 73 should be "warn" instead of "error"

**Review by dcpavel — APPROVED** [review]

**Comment by ChTiSh** [comment]
Do not merge this until all PRs and WIP cleared.

**Pull request merged**
