### PR TITLE
#379 Add Custom Node Styles to Nodes

### LINKED ISSUE #379: Apply custom styles to Nodes and Edges on generation of a new LinktaFlow
**Related User Story**

**Related Tickets**

**Acceptance Criteria**

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

### PR DESCRIPTION
**Pull request by colinvandergraaf**
## Description

This PR applies our custom styles to nodes by adding the LinktaNode type to generated nodes.  

This PR also add the disable attribute to the Input field if 

Fixes #379 #389

## Type of change

- [x]  🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨  New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 Documentation update
- [ ] Other 🗒️ ______________

## How Can this be tested? Testing Plan to review this PR

Go to the output page of any Linkta flow and see Node Styles applied 

Screenshot 2024-10-01 at 9 47 27 AM

## Checklist:

- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [x] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [x] I have ensured that my pull request title is descriptive.

### CODE REVIEW

**Review by relandboyle — APPROVED** [review]
@colinvandergraaf This is exciting to see. Great work.

It looks like there are a couple of different border-radius mismatches on this component.
After your changes are merged, I'd like to rebuild the custom node. 

image
image

**Comment by chriswillsflannery** [comment]
couple nits but overall looks good:
- can we remove the blinking cursor style from the text when the node is highlighted (node text isn't editable this way so I feel like if anything the hover state of the cursor should be reversed: when it's not hovering over a node should be something more nondescript (like a cursor) and when it's hovering a node it should be the "hand" icon (or something which screams "this is a draggable element"

**Comment by relandboyle** [comment]
> couple nits but overall looks good:
> 
> * can we remove the blinking cursor style from the text when the node is highlighted (node text isn't editable this way so I feel like if anything the hover state of the cursor should be reversed: when it's not hovering over a node should be something more nondescript (like a cursor) and when it's hovering a node it should be the "hand" icon (or something which screams "this is a draggable element"

@chriswillsflannery  Those are good points. We're going to have 10-20 new issues relating to node/edge styling and behavior. This PR was mainly about applying styles that were defined about four months ago.

**Review by kinskiwu — APPROVED** [review]
Great job! Excited for this milestone PR!

**Comment by colinvandergraaf** [comment]
Thanks for the comments on this I've created a [working issue](https://github.com/Linkta-org/core/issues/412) mentioning the changes suggested here and from standup earlier this week

**Pull request merged**
