### PR TITLE
LINKTA-72: Configued tsconfig file

### PR DESCRIPTION
**Pull request by zhiyi15**
Description:
completed tsconfig file added to project root directory

Fixes # LINKTA-72

Type of change:
- New feature(non-breaking change which adds functionality)

How Has This Been Tested? :
Not yet

Checklist:
- I have performed a self-review of my own code.
 - I have commented on my code, particularly in hard-to-understand areas.
 - I have made corresponding changes to the documentation.

Additional Information:
I commented out "path" and "alwaysStrict" options for now. Adjustments can be made once we start MVP coding phase.

### CODE REVIEW

**Review by LucieSeidler — APPROVED** [review]

**Review by dcpavel — CHANGES_REQUESTED** [review]
Why are we only including the files in src? what about the server files?

I think I mentioned this elsewhere, but target of ES2016 is both 1 version above ES6 (widely compatible) and 6 versions behind the latest ES2022. Why choose ES2016?

Do we want a single rootDir, or multiples? https://www.typescriptlang.org/tsconfig#rootDirs

**Comment by zhiyi15** [comment]
Hey Darren, thank you for reviewing!!

1) It seems like that Linkta is a Typescript project.. If so, we might not need the include option after all. I was referencing a past project of mine when I was working on this task, and just realized that project was a JavaScript project. 

2) That's my mistake, I meant to put ES6 as it's the safest option. I did some research after you pointed out. I think the next best option would be ES2021. What do you think?  [https://www.learningtypescript.com/articles/why-increase-your-tsconfig-target](url) & [https://gist.github.com/Julien-Marcou/156b19aea4704e1d2f48adafc6e2acbf](url)

3) I am open to that idea. As for now, I think rootDir works just fine, but I'm happy to add rootDirs option and comment it out in the file for future update once we start adding more code to the project directory.

**Review by AnatoliySokolov98 — CHANGES_REQUESTED** [review]
Id consider adding no unused params, no unused locals to have more type safety.

Also I think we need a jsx field to tells what to do with jsx elements which I believe should be set to preserve for next projects but you can double check.

We also need to add tsx type into include.

As Darren said, we probably want to have a root folder or multiple, so it might be a good idea to split this up into a server config and a client config for further customization.  That would make it easier to handle the server and client separately and uniquely.

**Comment by zhiyi15** [comment]
Thanks guys! I have made changes based on the comments. 
Take a look and let me know if you have any questions.

**Comment by AnatoliySokolov98** [comment]
I think this looks good, would have to look further when we actually start writing.
I do believe you need the jsx option though.  https://www.typescriptlang.org/tsconfig#jsx
Can correct me if I'm wrong on that one.

**Comment by zhiyi15** [comment]
You are right! I didn't catch it the first time you mentioned.  Just added the jsx option. can you see all the new changes? I couldn't see anything on my end.. no new commits on gh at all..

**Comment by AnatoliySokolov98** [comment]
I can't see the changes last commits 4 hours ago.

**Comment by zhiyi15** [comment]
I can see the new commits now! I got multiple Run failed notifications from GH because something is wrong in the .github/workflows/staging.yaml file.
You should be able to view the new changes now. Let me know if you have any questions!

**Review by AnatoliySokolov98 — APPROVED** [review]
Looks good, can modify later as needed

**Review by dcpavel — APPROVED** [review]
This looks good to me now. Thanks for catching the missing parameters, Anatoliy.

**Pull request merged**
