### PR TITLE
LINKTA-24: Adding system design diagram for MVP to docs

### PR DESCRIPTION
**Pull request by lomeintheory**
Per Chen's request, I'm making a PR to get eyes on our system design. This isn't a finished diagram, just what I have so far, so I'd appreciate any feedback.

### CODE REVIEW

**Review by LucieSeidler — COMMENTED** [review]
Server will communicate with Firebase directly, client will request token of backend and backend will provide authentication

**Review by PB-Liu — COMMENTED** [review]
It is unclear to me where the user should save their token/tree, assuming we have going to have this functionality. The same MongoDB? Or another database?

**Comment by relandboyle** [comment]
@PB-Liu Can you clarify "token/tree"? In my mind these are two completely different things.

There may not be any token, per se, if the server is managing sessions. The server can provide a session ID, and the client can store it in a browser cookie. If there is a token, the client would store it in Local Storage.

If the "tree" means the application state, I'm guessing that would be stored on the DB. And there's only one DB as far as I know.

@LucieSeidler @ChTiSh Does that sound about right?

**Comment by ChTiSh** [comment]
My understanding with authentication and database aligns with you @relandboyle. I'm a little confused too.

**Comment by PB-Liu** [comment]
@relandboyle Good call. I was assuming "token" and "tree" are indeed the same thing, probably because I misunderstood the diagram: on the diagram, the client requested token/tree from the server, the server makes an API call to Germini, which generates and returns the (requested) token, and the server send _that_ token/tree to the client. 
So I was assuming the "token" here has nothing to do session (otherwise why would Germini returns it) , but is whatever the client request and receives eventually---that is, a data structure that represents the tree the client will see. 
My understanding could be very wrong --- feel free to correct/clarify @lomeintheory

**Comment by LucieSeidler** [comment]
I agree on removing the word token. I would phrase it as "send prompt" , "receive tree structure" or tree data or something like that. The backend will process the prompt and use the Linkta Gemini API Key to make a call to Gemini and then parse through the data and store it / send it to the front end.

**Comment by ChTiSh** [comment]
I think the token on the diagram might be referring to the scenario of the client holding the authentication/access token and communicate with server with access token. This goes back to our morning discussion 
Here is diagram:
https://docs.oracle.com/cd/E88140_01/books/RestAPI/RestAPI_Overview13.html

**Comment by relandboyle** [comment]
@PB-Liu Ah! I see. Maybe I was confused because the word "token" is commonly used in two different contexts.

@LucieSeidler I like this convention. The client doesn't deal with Gemini API tokens. The client sends string prompts and receives trees.

Does the client deal with auth tokens? If not (if it uses session cookies) then we can assume the words "token" and "client" generally won't be seen or used together. If the client does handle auth tokens then we can always refer to "auth tokens" and "Gemini tokens", for example, to keep them distinct.

**Comment by dcpavel** [comment]
I am still unsure of how Firebase will be integrated. Further research on my part has revealed that there is a firebase UI you can include in the FE that will authenticate the user: https://firebase.google.com/docs/auth/web/firebaseui

It appears that this may create a user that can also be accessed by the backend for storing and retrieving user data: https://firebase.google.com/docs/auth/web/manage-users

I am still not 100% sure on how this all integrates and if there are any other security vulnerabilities exposed by leaving authentication entirely on the client. Because of this, I'm not sure where on the diagram "Auth service" should be.

We are set on Firebase for auth, however, and I would like to see that indicated on the diagram, the same way that MongoDB, Redis, and Gemini are.

**Comment by kinskiwu** [comment]
> Agree with @dcpavel we are not 100% sure how we will use firebase but can probably add it to the diagram.

I agree with @dcpavel too. We can always update it later. Good to have an updated diagram containing all the core tech.

**Comment by lomeintheory** [comment]
Thanks for all the feedback! I've added Firebase to the diagram and rephrased "token" accordingly. I've also replaced the Redis icon with React Query, which I believe we're set on using for client side caching. 

Screen Shot 2024-03-12 at 8 56 28 PM

**Review by dcpavel — CHANGES_REQUESTED** [review]
You linked a file in the comments that looks good for now. This diagram may change, so I don't think we need to be more technical than your last document. That diagram is not what is set to be merged, however. Please replace it in the merge commit (you can just update the branch you are trying to merge with the new image).

**Comment by lomeintheory** [comment]
Branch has been updated with the revised diagram. Let me know if everything looks good to merge!

**Review by LucieSeidler — APPROVED** [review]

**Review by dcpavel — APPROVED** [review]

**Pull request merged**
