### PR TITLE
Proposal for Security Best Practices Documentation 

### PR DESCRIPTION
**Pull request by kinskiwu**
## Description

This PR introduces a new markdown file, `SECURITY_BEST_PRACTICES.md` under `/docs`, dedicated to outlining security best practices for our development teams. 

#### Content Overview
- **Frontend Security**: XSS protection, CSRF protection, data handling and storage, HTTP headers, API security, dependency management, and build & deployment practices.
- **Backend Security**: Authentication, session management, input validation and sanitization, database security, access control, infrastructure, and error handling and logging.
- **General Security Practices**: Code reviews and training, encryption and data protection, access control, compliance and audits.

Fixes #[Linkta-87](https://linkta.atlassian.net/browse/LINKTA-87?atlOrigin=eyJpIjoiMjg5YjZkZGMyY2JlNGQ3YTlmYzUzYzczOTQxYTMxMGIiLCJwIjoiaiJ9)

## Type of change

Please delete options that are not relevant.
- [x] Documentation update

#### Request for Feedback
I'm seeking feedback on the following aspects of the document:
- **Completeness**: Are there any critical security best practices missing that should be included?
- **Accuracy**: Does the document accurately describe the best practices?
- **Clarity and Style**: Is the information presented clearly? Is the document easy to read and understand?
- **Practicality**: Are the recommendations practical and feasible to implement in our projects?

Looking forward to your feedback and suggestions to make our security practices more effective.😊

### CODE REVIEW

**Comment by relandboyle** [comment]
@kinskiwu This looks good but I have one comment.

I think it's good practice to perform input validation and sanitization on both the client and the server. Was this omitted intentionally from frontend in the security document?

**Comment by kinskiwu** [comment]
> @kinskiwu This looks good but I have one comment.
> 
> I think it's good practice to perform input validation and sanitization on both the client and the server. Was this omitted intentionally from frontend in the security document?

Good eye. I had it in a previous version but somehow omitted it by accident. I'll update the doc.

**Comment by kinskiwu** [comment]
Just push some changes to make the doc more readable.🤓

**Review by LucieSeidler — COMMENTED** [review]
Thank you for developing this!

**Review by dcpavel — APPROVED** [review]
A lot of these were not properly addressed in Codesmith. Make sure you familiarize yourself with them when dealing with security. I would also like to add security for DevOps. Using CI/CD and deploying to Dreamhost will involve using SSH to move files and run scripts. We should ensure that the user that is updating the server does not gain permissions outside the needed scope (Dreamhost already prevents sudo access, but we shouldn't grant extra permissions, e.g. to write to long term storage spaces).

**Comment by kinskiwu** [comment]
> A lot of these were not properly addressed in Codesmith. Make sure you familiarize yourself with them when dealing with security. I would also like to add security for DevOps. Using CI/CD and deploying to Dreamhost will involve using SSH to move files and run scripts. We should ensure that the user that is updating the server does not gain permissions outside the needed scope (Dreamhost already prevents sudo access, but we shouldn't grant extra permissions, e.g. to write to long term storage spaces).

Thanks for the suggestions! I made a new section for DevOps and infrastructure. Let me know what you think.

**Review by relandboyle — APPROVED** [review]

**Pull request merged**
