### PR TITLE
Refactor UserInputList and Options Menu Anchor for Better Accessibility & UI/UX

### LINKED ISSUE #415: Flyout Menu - Alignment with side bar
**Related User Story**

**Related Tickets**

**Acceptance Criteria**

- The menu previously we well aligned with the button and with the border of the side nav
- Consider restoring to that state with improved alignment

Screenshot 2024-10-04 203703

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

### PR DESCRIPTION
**Pull request by kinskiwu**
## Description

- Refactor `UserInputList` structure 
  - wrap `ToolTip` around `ListItemText` instead of `ListItemButton` for better accessibility & UX (so ToolTip only shows when hovering over text and not the whole button)
  - move `OptionsMenu` inside List item
- Refactor `OptionsMenu` 
   - move the anchor element from `IconButton` to its parent UI so the menu is aligned correctly
   - updated the CSS to maintain consistent border size and prevent content shifts on hover 
- Apply standardized focus styling to buttons and text input in dialogs
- Disable the save button when no changes to the input title  

Fixes #415 #416 #414

## Type of change

- [X] Other 🗒️ Refactor

## How Can this be tested? Testing Plan to review this PR
- Spin up app
- Hover over UserInputList -> ToolTip (only appears when hovering over text but not IconButton)
image

- Click Sidenav -> Options Menu (no overlapping border, no gap between hover background color and menu border, no shifting of content)
image

- Click Rename 
 -> Save button disabled unless changes made to input title
Rename Title
 -> Click input & buttons (light yellow border appears)
 
## Checklist:

- [X] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [X] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [X] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [X] I have ensured that my pull request title is descriptive.

### CODE REVIEW

**Review by colinvandergraaf — APPROVED** [review]
Anchor styling fix looks good! Is the autofocus the gray circle below or was this introduced elsewhere? 
Screenshot 2024-10-08 at 1 20 54 PM

**Comment by kinskiwu** [comment]
@colinvandergraaf Thanks for the review! That's a good point. It was not intentional and I just fixed the styling.

**Comment by chriswillsflannery** [comment]
"Recent" menu options currently have no styling applied when focused/tab accessed:



https://github.com/user-attachments/assets/22c37b24-19dd-40c8-a5ba-bf3e7a0240bd

**Comment by chriswillsflannery** [comment]
feel like the focus styles on these buttons are a little odd

Screenshot from 2024-10-15 11-36-02

**Comment by kinskiwu** [comment]
@chriswillsflannery Thanks for the thorough review! I updated the CSS and now the text input & all buttons in Dialogs have a standardized focus styling)
image
image
image

I wasn't able to reproduce this shadow effect, was it related to focus or other effect? (I wonder if it is related to the transition effect we have for the buttonBase styling)
image
```css
.buttonBase {
  transition: background-color 0.3s ease;
}
```

**Comment by chriswillsflannery** [comment]
@kinskiwu yeah that focus effect only appears when focusing via keyboard nav

**Review by chriswillsflannery — APPROVED** [review]

**Review by relandboyle — APPROVED** [review]
Fabulous.

**Pull request merged**
