### PR TITLE
Fix 285 ensure correct rendering of linktaflow in react flow component

### LINKED ISSUE #285: Ensure Correct Rendering and Styling of LinktaFlow in React Flow Component
Follow-up task from #275 

**Description**
We need to ensure the LinktaFlow object fetched from the API is correctly rendered in the React Flow component with the appropriate layout and styling. The current integration has issues with layout positioning and styling of nodes and edges.

**Acceptance Criteria**
- Data Mapping: All necessary properties (e.g., positions, labels, colors) should be included in the nodes and edges.
- Layout Application: The layout algorithm (Dagre) should correctly position nodes. 
- Rendering and Styling: Nodes and edges should be rendered correctly in the React Flow component. Nodes and edges should have the correct styling applied (e.g., colors, labels).

### PR DESCRIPTION
**Pull request by LucieSeidler**
Renders correct linktaflow components connecting nodes to edges

Fixes #285 

## Type of change

- [x]  🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨  New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 Documentation update
- [ ] Other 🗒️ ______________

## How Can this be tested? Testing Plan to review this PR

Run application and generate a new user input, confirm that new inputs load edges correctly. Previous test data may not have necessary information stored and may not generate correct edge components

## Checklist:

- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [x] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [x] I have ensured that my pull request title is descriptive.

### CODE REVIEW

**Review by kinskiwu — COMMENTED** [review]
Thanks for the good work solving this bug! Just a couple of minor things:
1. Please also address the following acceptance criteria either in this PR or create a new ticket that links to this PR and #285:

`Rendering and Styling: Nodes and edges should be rendered correctly in the React Flow component. Nodes and edges should have the correct styling applied (e.g., colors, labels).`

2. In this PR:
- Unser `Checklist`, please ensure to always check the last three items.
- Under `Type of change`, please remove the spacing in the [ x] so that the checkbox gets rendered correctly.

**Comment by kinskiwu** [comment]
FYI for code reviewers: if you do not see a LinktaFLow associated with a UserInput, pls generate a new LinktaFlow by clicking `Explore a new topic`. You may want to try a few times until you get a LinktaFlow successfully (check the Chrome dev tool to ensure you're not getting axios errors). And make sure to refresh the page to get the updated UserInput on the SideNav.

**Comment by LucieSeidler** [comment]
> 1. Please also address the following acceptance criteria either in this PR or create a new ticket that links to this PR and [Ensure Correct Rendering and Styling of LinktaFlow in React Flow Component #285](https://github.com/Linkta-org/core/issues/285):
> 
> `Rendering and Styling: Nodes and edges should be rendered correctly in the React Flow component. Nodes and edges should have the correct styling applied (e.g., colors, labels).`

Currently there is no indication that the application is not loading components with applied styling. Correct styling for nodes will be done under a different ticket given that it's not a "fix"

**Review by kinskiwu — APPROVED** [review]

**Comment by kinskiwu** [comment]
@LucieSeidler and I identified that when a user signs up, the path correctly switches to /generate, but sometimes the UI continues to display the auth page. Since this issue doesn't impact the functionality of this feature I created a bug ticket for it #313

**Review by colinvandergraaf — APPROVED** [review]
I tried this a few times and kept getting 500 server errors when submitting the UserInputForm. I imagine it's something on my end given the few lines of changes involved here.  Looks good!

**Pull request merged**
