### PR TITLE
Refactor: Node Style

### LINKED ISSUE #419: Linkta Node Styles
**Related User Story**

**Related Tickets**

**Acceptance Criteria**

- Correct mismatching border radius settings
- Consider UI/UX and evaluate hover behavior, color contrast for accessibility, border settings
- Move custom node styles to CSS modules

Screenshot 2024-10-01 133631
Screenshot 2024-10-01 133430

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

### PR DESCRIPTION
**Pull request by kinskiwu**
## Description
- Corrected mismatched border
- Updated Node color
- Converted inline styles to CSS modules (LinktaNode + Flow)

Fixes #419 

## Type of change
- [X] Other 🗒️ Refactoring

## How Can this be tested? Testing Plan to review this PR
- Spin up app
- Create a LinktaFlow
- Observe new styles in Nodes
Before:
image

After:
image

## Checklist:

- [X] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [ ] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [X] I have ensured that my pull request title is descriptive.

### CODE REVIEW

**Review by relandboyle — CHANGES_REQUESTED** [review]
@kinskiwu I think this PR addresses all of the requested changes from the linked issue. However, I think there are still some stranger border interactions on the left side. This may be addressed in #418, depending on who takes it.

Also it appears that you changed the primary background color of the node. I know a few people have concerns regarding contrast, and that should be addressed, but I think a change like this requires team alignment. 

image

**Comment by kinskiwu** [comment]
@relandboyle reverted backed to original color
image

**Review by chriswillsflannery — APPROVED** [review]
LGTM

**Review by chrisr0892 — APPROVED** [review]
Looks good!

**Review by relandboyle — APPROVED** [review]

**Pull request merged**
