### PR TITLE
Update data models for users, user input, and Linkta flow to reflect new data relationships

### LINKED ISSUE #94: Improve Data models for UserInput Model and LinktaFlow Model
## Acceptance criteria
- Ensure data consistency, integrity, and scalability
- Refine relationships and associations with other models
- Optimize for performance and efficient querying
- Collaborate with the team to gather feedback and incorporate necessary improvements

## Additional note
Expect the design will change during the sprint
https://github.com/Linkta-org/core/blob/dev/.github/docs/MVP_SYSTEM_DESIGN_DOCUMENTATION.md
https://github.com/Linkta-org/sandbox/pull/21/files

### PR DESCRIPTION
**Pull request by AaronDreyfuss**
## Description

Fixes # (issue)

## Type of change

- [ ]  🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨  New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 Documentation update
- [ ] Other 🗒️ ______________

## Checklist:

- I have performed a self-review of my own code.
- I have commented on my code, particularly in hard-to-understand areas.
- My changes generate no new warnings.
- Any dependent changes have been merged and published in downstream modules.
- I have ensured that my pull request title is descriptive.

### CODE REVIEW

**Review by zhiyi15 — APPROVED** [review]
Thank you Aaron!

**Review by ChTiSh — APPROVED** [review]

**Comment by relandboyle** [comment]
@ChTiSh @zhiyi15 @AaronDreyfuss This looks good to me and I wouldn't hesitate to merge, but I have a question.

Do we need data models for Node and Edge in the /types folder? Is this redundant with the types provided by React-Flow?

**Comment by AaronDreyfuss** [comment]
> @ChTiSh @zhiyi15 @AaronDreyfuss This looks good to me and I wouldn't hesitate to merge, but I have a question.
> 
> Do we need data models for Node and Edge in the /types folder? Is this redundant with the types provided by React-Flow?

React-Flow does have types for Node and Edge, but we have some extra fields and relationships in our custom models that fit our app better. For example, we have fields like label, draggable, and resizing in Node, and sourceHandle and targetHandle in Edge. Plus, our nodes and edges are linked to specific UserInput and LinktaFlow documents, which React-Flow’s types don’t cover.

**Comment by relandboyle** [comment]
@AaronDreyfuss If you'll check the Node and Edge API reference pages I think you'll find that all of those properties are covered by the provided types.

https://reactflow.dev/api-reference/types/node
https://reactflow.dev/api-reference/types/edge

Our nodes and edges are not linked to specific UserInput and LinktaFlow documents. A LinktaFlow includes an array of type: Node and an array of type: Edge but I'm not seeing a need to maintain our own replica type definitions.

**Comment by AaronDreyfuss** [comment]
> @AaronDreyfuss If you'll check the Node and Edge API reference pages I think you'll find that all of those properties are covered by the provided types.
> 
> https://reactflow.dev/api-reference/types/node https://reactflow.dev/api-reference/types/edge
> 
> Our nodes and edges are not linked to specific UserInput and LinktaFlow documents. A LinktaFlow includes an array of type: Node and an array of type: Edge but I'm not seeing a need to maintain our own replica type definitions.

You're right, thank you for pointing that out. In that case, we can remove those types from the data models file.

**Pull request merged**
