### PR TITLE
Refactor: updated user input from left sidebar with tooltip

### PR DESCRIPTION
**Pull request by nparmar1**
I added a tooltip to the left sidebar for user input items so that when a user hovers over an item, the full text is displayed. This is especially useful for longer user inputs that are truncated with an ellipsis.

Screenshots:

Tooltip without scrollbar:
Screen Shot 2024-09-30 at 1 57 10 PM

Tooltip with scrollbar:
Screen Shot 2024-09-30 at 1 59 01 PM

Fixes # (issue)

## Type of change

- [ ]  🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨  New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 Documentation update
- [ ] Other 🗒️ ______________

## How Can this be tested? Testing Plan to review this PR

- [x] Where in the app does this change take place?
- From the root dir, start up the app (both client and server)
- [x] What are the steps to test this change?
- Sign in as a user
- At the top left of the sidebar, click 'Explore a New Topic'
- Enter a very long input and click 'Generate' or click on one of the longer examples provided. E.g. 'Taxonomy of Living Organisms'
- The user input will generate on the main content page on the left sidebar underneath 'Recent' you'll see the user input
- Hover your mouse pointer over the text and then outside of the text (within the button)
- [x] What is the expected output?
- The tooltip will display

## Checklist:

- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [x] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [x] I have ensured that my pull request title is descriptive.

### CODE REVIEW

**Review by kinskiwu — COMMENTED** [review]
Awesome job on your first PR! Looks solid overall. Just a few things:
- Please complete the PR template when you get a chance and link it to the original issue. You can read the instructions and check other open PRs to see how it's done.
- Could you move the tooltip to the right? It’s currently covering some of the content.
- Appreciate the comment you added, but it might be uncessary for styling.

**Review by chriswillsflannery — APPROVED** [review]
LGTM just echoing the same comments as above, in this kind of UI update where there's a new element introduced it's useful to include a screenshot on the PR

**Review by relandboyle — CHANGES_REQUESTED** [review]
@nparmar1 Great job identifying that the scroll bar can potentially affect the appearance of the tooltip. I hadn't thought of that.

I think it looks better with a positive y in the offset value. An offset of [0, 5] looks good to my eye. What do you think?

image

**Comment by nparmar1** [comment]
> @nparmar1 Great job identifying that the scroll bar can potentially affect the appearance of the tooltip. I hadn't thought of that.
> 
> I think it looks better with a positive y in the offset value. An offset of [0, 5] looks good to my eye. What do you think?
> 
> image

@relandboyle Ah, yes, this looks good. I was concerned the tooltip looking odd without the scrollbar and a positive Y value, but it seems fine. I'll make the changes.

**Review by chriswillsflannery — APPROVED** [review]
LGTM

**Review by relandboyle — APPROVED** [review]

**Pull request merged**
