### PR TITLE
Feature/set up routing for navbar links

### LINKED ISSUE #142: Set up routing for navbar links
Navbar links should navigate to their intended paths when clicked

### PR DESCRIPTION
**Pull request by lomeintheory**
This is intended to be a quick update to the routes for the navbar links. The "user profile" link routes to the '/sign-in' path for now, and "Explore a New Topic" routes to the '/generate' path.

Fixes #142 

## Type of change

- [x] ✨  New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Ran on localhost to check if links navigate to their intended paths

## Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [ ] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [ ] I have ensured that my pull request title is descriptive.

### CODE REVIEW

**Review by relandboyle — APPROVED** [review]

**Comment by relandboyle** [comment]
@lomeintheory What about the links at the bottom of the nav bar? And what about the compact links when the side nav drawer is closed?

**Comment by lomeintheory** [comment]
> @lomeintheory What about the links at the bottom of the nav bar? And what about the compact links when the side nav drawer is closed?

Good catch. I'll take care of the compact links. I couldn't find placeholders for the links at the bottom ("Help and Feedback" and "Settings"), but I can add them to the layout config as part of this ticket. Thoughts?

**Comment by relandboyle** [comment]
Let Figma guide you.

**Comment by relandboyle** [comment]
@lomeintheory I think it would be good to also get rid of all the placeholder elements as part of this PR. What do you think?

**Comment by lomeintheory** [comment]
> @lomeintheory I think it would be good to also get rid of all the placeholder elements as part of this PR. What do you think?

Good call. I didn't notice that those components were created already.

**Review by ChTiSh — APPROVED** [review]

**Review by ChTiSh — APPROVED** [review]
Thank you @lomeintheory

**Pull request merged**
