### PR TITLE
LINKTA-20: Backend Dependencies Added

### PR DESCRIPTION
**Pull request by LucieSeidler**
Description
Backend Dependencies added to package.json file

Fixes # LINKTA-20

Type of change
Please delete options that are not relevant.

 Documentation update
How Has This Been Tested?
No tests needed

Checklist:
Before submitting your pull request, please review the following checklist:

- [ X ]  I have performed a self-review of my own code.
- [ ]  I have commented on my code, particularly in hard-to-understand areas.
- [ ]  I have made corresponding changes to the documentation.
- [ ]  My changes generate no new warnings.
- [ ]  Any dependent changes have been merged and published in downstream modules.

Additional Information:
Potential issue with current Next.Js version, receiving warning upon npm install. Will need to discuss implications with team.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'next@14.1.3',
npm WARN EBADENGINE   required: { node: '>=18.17.0' },
npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.5.1' }
npm WARN EBADENGINE }

### CODE REVIEW

**Comment by ChTiSh** [comment]
Next.js version 14.1.3 requires Node.js version 18.17.0 or newer.
The Node.js version 18.16.0, are there other dependencies require node to be 18.16.0?

**Comment by dcpavel** [comment]
I'm sorry I'm late on reviewing this.
cookieparser is on 0.1.0 and was last worked on 10 years ago
cookie-parser is on 1.4.6 and was last updated 2 years ago
I think we want cookie-parser, not cookieparser

I am happy to be wrong, but we may need:
@types/node
@types/cookie-parser
@types/cors
@types/express

**Review by dcpavel — APPROVED** [review]
This looks good to me for now. I'm sure that changes may be made during development, but this seems comprehensive at this time.

**Review by AnatoliySokolov98 — CHANGES_REQUESTED** [review]
All type dependencies are dev dependencies and should go into dev folder I believe.

**Review by dcpavel — APPROVED** [review]
I think this is everything.

I believe that Anatoliy may be right that the @types should be in the dev dependencies. You can see that here:
https://www.geeksforgeeks.org/difference-between-dependencies-devdependencies-and-peerdependencies/

We can always move them if we encounter a problem during push to production.

**Review by AnatoliySokolov98 — APPROVED** [review]
Looks Good

**Pull request merged**
