### PR TITLE
adds favicon coverage to most browsers & devices

### LINKED ISSUE #104: Implement a favicon
**Related User Story**

**Related Tickets**

**Acceptance Criteria**

The favicon is the image used to represent the Linkta application in browser tabs, etc.
Follow best practices to provide a clearly identifiable icon in multiple resolutions.

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

### PR DESCRIPTION
**Pull request by bjpreston**
Adds favicon (Linkta logo) optimized for popular browsers (Chrome, Safari, Firefox, Edge) and mobile (iOS, android) 

Fixes #104 

## Type of change

- [ ]  🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨  New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 Documentation update
- [ ] Other 🗒️ ______________

## How Has This Been Tested?

- [x] manual testing

## Checklist:

- [x] I have performed a self-review of my own code.
- [] I have commented on my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [] Any dependent changes have been merged and published in downstream modules.
- [x] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [x] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [x] I have ensured that my pull request title is descriptive.

## Additional Information:

#faviticket

### CODE REVIEW

**Review by relandboyle — APPROVED** [review]

**Review by colinvandergraaf — COMMENTED** [review]
Screenshot 2024-05-31 at 10 48 41 AM
Is the blue icon what we're going for in safari?  Why is this different than other browsers?

**Comment by bjpreston** [comment]
> Screenshot 2024-05-31 at 10 48 41 AM Is the blue icon what we're going for in safari? Why is this different than other browsers?

Safari is displaying the proper favicons on my machine. Not sure why your Safari is choosing the asset meant for the Macbook TouchBar
Screenshot 2024-05-31 at 3 11 27 PM
Screenshot 2024-05-31 at 3 11 40 PM

**Review by ChTiSh — APPROVED** [review]
Looks good!!!

**Comment by relandboyle** [comment]
@bjpreston @colinvandergraaf 

I noticed that the PR includes a bunch of .png images and one .svg (safari-pinned-tab.svg) and in the GitHub preview, that .svg is all black (all one color). It's also a much smaller file size than the .svg files in the Linkta /assets folder.

Is this .svg corrupted in some way?
Does Safari require an .svg file specifically?

**Comment by relandboyle** [comment]
@bjpreston @ChTiSh 

Good job on this but there are still a couple of small issues.

1. The background is still not transparent. I'm not sure how these images are being generated, but this is something I can help with. Let's Zoom and analyze the process.

2. The image files should not include padding. Consider: if I'm choosing the 256px x 256px logo image, and the image includes about 30% padding, then the visible image is closer to 177px x 177px. 

image

**Pull request merged**
