### PR TITLE
Added Confirm Password Field to Sign Up Page

### PR DESCRIPTION
**Pull request by nparmar1**
## Description
I added a 'confirm password' field to the Sign Up page, requiring users to enter their password twice for confirmation before creating their account.

- [x] ✨  New feature (non-breaking change which adds functionality)

## How Can this be tested? Testing Plan to review this PR

- Switch to feature-331-add-password-conf branch
- Spin up app (both client and server)
- Make sure you're signed out of your account and click 'Sign Up'
- Enter your name
- Enter your email
- Enter a desired password
- Intentionally enter a password that doesn't match your password
- You should an see an error underneath the 'confirm password' field in red stating 'Passwords do not match'

Screenshot of new field, 'confirm password':
Screen Shot 2024-10-06 at 11 55 12 AM

Screenshot of field with password not matching:
Screen Shot 2024-10-06 at 11 56 25 AM

- [x] Where in the app does this change take place?
- SignUpPage component in the client folder

## Checklist:

- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [x] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [x] I have ensured that my pull request title is descriptive.

### CODE REVIEW

**Review by relandboyle — CHANGES_REQUESTED** [review]
@nparmar1 Good work. This forces the user to confirm their password when signing up.

Rather than validating on form submit, do you think it would be better to validate on each keystroke? This would notify the user of a mismatch earlier and give them an idea of where they made a typo.

Can we improve the helper text on the confirm password input? Rather than "Please enter confirm password" perhaps something like "Please confirm password" or "Re-enter password"?

**Comment by nparmar1** [comment]
> @nparmar1 Good work. This forces the user to confirm their password when signing up.
> 
> Rather than validating on form submit, do you think it would be better to validate on each keystroke? This would notify the user of a mismatch earlier and give them an idea of where they made a typo.
> 
> Can we improve the helper text on the confirm password input? Rather than "Please enter confirm password" perhaps something like "Please confirm password" or "Re-enter password"?

Hey, Reland! The last meeting we had was suggested to look at other sites' Sign Up pages and their behaviors. Right now I feel like Amazon's Sign Up page is pretty similar to ours. But I'd like to hear your thoughts

**Review by kinskiwu — APPROVED** [review]
Good job. Works as intended. Sent you a DM about ways to consolidate the auth-related validators. 

@relandboyle Since the validation per keystroke was not part of the original ticket and this PR has been up for a while, how about we create a separate ticket to address this added feature?

**Comment by chriswillsflannery** [comment]
Hi all, will just throw my 2cents in here - I disagree with validating on each keystroke 

As an end user, I feel like it's a red herring to be shown an error state before you've actually done something wrong
In this I think it's more distracting than useful to be shown an error state before you've even finished typing

**Comment by nparmar1** [comment]
> Good job. Works as intended. Sent you a DM about ways to consolidate the auth-related validators.
> 
> @relandboyle Since the validation per keystroke was not part of the original ticket and this PR has been up for a while, how about we create a separate ticket to address this added feature?

Thanks, @kinskiwu! I just applied those changes.

**Review by kinskiwu — APPROVED** [review]

**Review by chriswillsflannery — APPROVED** [review]

**Review by relandboyle — APPROVED** [review]

**Comment by relandboyle** [comment]
> Hi all, will just throw my 2cents in here - I disagree with validating on each keystroke
> 
> As an end user, I feel like it's a red herring to be shown an error state before you've actually done something wrong In this I think it's more distracting than useful to be shown an error state before you've even finished typing

@chriswillsflannery FWIW I did not propose displaying an error before an error occurs. If my password is "password" and I type "past", then an error has occurred on the fourth keystroke. "past" is not a valid substring of "password" beginning at the 0th index. If I type "last" then an error has occurred on the first keystroke. As a user, I'd rather be alerted immediately than to wait until I finish typing in "lastword" and click the submit button.

@nparmar1 All of that said, I'm happy to skip that functionality for now and merge this PR. I think you met the requirements for this issue. Based on our call tonight I still hope to greatly improve the user experience with our next effort.

**Pull request merged**
