### PR TITLE
LINKTA-162: docs: Create basic template for writing research or decision documentation

### PR DESCRIPTION
**Pull request by ChTiSh**
## Description
Create a template for documentation of our research/decisions

Fixes # (issue) 162

## Type of change

- [ ]  🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨  New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] 📝 Documentation update
- [ ] Other 🗒️ ______________

## How Has This Been Tested?

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have reviewed the [**Security Best Practices Document**](SECURITY_BEST_PRACTICES.md).
- [ ] I have followed the [**Naming Conventions Guide**](NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [x] I have ensured that my pull request title is descriptive.

### CODE REVIEW

**Review by relandboyle — COMMENTED** [review]
@ChTiSh Is this different from having a spike story in Jira?

**Comment by ChTiSh** [comment]
They are the same thing, haha, just trying to keep better records on github for future references and contributors

**Comment by relandboyle** [comment]
Well, I won't stop you. I'll just say in my experience we don't sync anything from spike stories. We have a brief write-up or notes in Jira, and if it's something the team needs to know then maybe there's a short presentation.

**Review by relandboyle — APPROVED** [review]

**Comment by ChTiSh** [comment]
haha, @relandboyle thank you!! I'm gonna pull @colinvandergraaf in for this discussion.

**Review by kinskiwu — APPROVED** [review]
Thank you Chen!

**Pull request merged**
